services:
  - type: web
    name: raam-setu
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn setu_coin.wsgi:application
    envVars:
      - key: DATABASE_URL
        value: postgres://CHANDAN:HA61*#gsjga57@%@429haf@582&%2#uabYuwHHhrwWeywv@123@postgreSQL:5432/RAAM
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
